---
- hosts: localhost
  connection: localhost
  roles:
   - base
   - desktop
   - tor
   - role: gantsign.keyboard
     # European keyboard model (pc105 is widely used outside Europe as well)
     keyboard_model: pc105
     # Layout for Great Britain / United Kingdom
     keyboard_layout: de