---
- name: "Add torproject apt-key"
  apt_key:
    keyserver: keys.gnupg.net
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: "Add torproject repository"
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org jessie main
    state: present
    filename: 'torproject'

- name: "Install Tor & Dependencies"
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - deb.torproject.org-keyring
    - tor
    - tor-arm

- name: "Enable tor"
  service:
    name: tor
    enabled: yes

- name: "Configure tor"
  lineinfile:
    path: /etc/tor/torrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#AutomapHostsOnResolve", line: "AutomapHostsOnResolve 1" }
    - { regexp: "^#TransPort", line: "TransPort 9040" }
    - { regexp: "^#DNSPort", line: "DNSPort 53" }
  notify: "Restart Tor"

- name: "Configure nameserver"
  copy:
    src: "resolv.conf"
    dest: "/etc/resolv.conf"

- name: "Make tor-firewall and rc.local executable"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/rc.local
    - /usr/local/bin/tor-firewall.sh

- meta: flush_handlers